### ISSUE TITLE
[CM][Bug] Enable inference for `ResNet-50` with TVM backend

### ISSUE THREAD

**Issue by KJlaccHoeUM9l** [Deelvin/ck#1]
When trying to run [this tutorial](https://github.com/mlcommons/ck/blob/master/docs/tutorials/sc22-scc-mlperf-part3.md) using the TVM backend, the following types of errors occur:
1. Structural errors associated with CM - fixed in [PR#632](https://github.com/mlcommons/ck/pull/632);
2. TVM inference related bugs - **investigation needed**.

It is necessary to investigate the second type of errors and prepare a PR to fix them.

**Comment by Ailurus1** [comment]
In `app-mlperf-inference` there is fixed batchsize (32) for tvm-onnx backend that sets the value of env variable `CM_MLPERF_LOADGEN_MAX_BATCHSIZE` and should be passed through `app-mlperf-inference-reference` to `get-ml-model-resnet50-tvm` for setting env variable `CM_ML_MODEL_MAX_BATCH_SIZE`.  
Probably it should passed using `batch_size.#` tag, but I didn't find the way we can use it for passing value through more than one script, so in #6 I just manually set the value of the variable `CM_ML_MODEL_MAX_BATCH_SIZE` as the value of `CM_MLPERF_LOADGEN_MAX_BATCHSIZE` in `app-mlperf-inference-reference` and after this action, the workflow began to complete without any errors.

**Comment by KJlaccHoeUM9l** [comment]
Hello @Ailurus1!
I started discussion in prepared draft.

**Comment by Ailurus1** [comment]
After merging [this PR](https://github.com/mlcommons/ck/pull/651) the workflow seems to work properly (at least for TVM installed via pip)

**Comment by Ailurus1** [comment]
> After merging [this PR](https://github.com/mlcommons/ck/pull/651) the workflow seems to work properly (at least for TVM installed via pip)

The problem was in the incorrect processing of `batch_size` tag. It was fixed in this PR via changing `tvm-model` in `app-mlperf-inference` to `mlperf-inference-implementation`, adding needed dependencies to `batch_size` processing in `app-mlperf-inference-reference` and replaced `bs` tag with `batch_size` so it is the same tag through the whole workflow
