### ISSUE TITLE
[MLPerf][BUG] Deadlock during inference with TVM backend

### ISSUE THREAD

**Issue by Ailurus1** [Deelvin/ck#13]
After introducing model tuning with MetaScheduler some deadlock began to occur at the inference stage. It is observed during running CM workflow for ResNet50 MLPerf Inference with TVM-ONNX backend (and during adding TVM-TFLite @Maximallnyi). The problem is caused by some problems with usage of Python process pool in `mlcommons/inference/vision/classification_and_detection/python/backend_tvm.py` for `batchsize` > 1. 
The inference works properly in 3 cases:
1) Without tuning
2) For `batchsize` = 1
3) After manually setting `arena_num` as 1, 2, ... (figure out when it stop working) with `arena_size` set as 1

**Comment by Ailurus1** [comment]
After replacing `Pool` from `multiprocessing` on `ProcessPoolExecutor` from `concurrent.futures` in [this commit](https://github.com/Deelvin/inference/commit/5616c5ecadc8503470f077d5beadcc84084eaa8f) the inference workflow started working correctly with any batchsize and proper number of threads. But there are still unresolved questions:  
1) What exactly caused deadlock with `Pool` from `multiprocessing`?
2) Why `arena_size` is manually set as `4` in `inference/vision/classification_and_detection/python/main.py`?

**Comment by KJlaccHoeUM9l** [comment]
cc @KJlaccHoeUM9l

**Comment by Ailurus1** [comment]
The problem was local (but on different devices) and related to hidden segmentation fault and unability to process it by `fork` start method in python `multoprocessing`.
It was occured only on laptops with not so strong CPUs and it works fine when running anywhere in one process.
When running with `fork` start method it cannot correctly catch segmentation fault caused by too big batchsize, but `spawn` start method can, so in [this](https://github.com/mlcommons/inference/pull/1395) PR the start method configuration was introduced for debugging purposes. To avoid segmentation fault on weak CPU better decrease batchsize.
[Discussion](https://github.com/Deelvin/inference/pull/1).

The batchsize should probably be configurable and the same for number of threads/processes that will be done in #20
