### ISSUE TITLE
[CM] Introduce tuning with MetaSchedule for ResNet50

### ISSUE THREAD

**Issue by Ailurus1** [Deelvin/ck#14]
Currently `ResNet50` MLPerf inference workflow in `CMind` just compiles model withut any tuning, but to get maximum performance we need to use modern `MetaSchedule`.

**Comment by KJlaccHoeUM9l** [comment]
cc @KJlaccHoeUM9l

**Comment by Ailurus1** [comment]
Implemented [here](https://github.com/mlcommons/ck/pull/693)
Close this ticket as the PR was merged
